/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_SanAngeles_PlayerThread */

#ifndef _Included_com_example_SanAngeles_PlayerThread
#define _Included_com_example_SanAngeles_PlayerThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_SanAngeles_PlayerThread_MIN_PRIORITY
#define com_example_SanAngeles_PlayerThread_MIN_PRIORITY 1L
#undef com_example_SanAngeles_PlayerThread_NORM_PRIORITY
#define com_example_SanAngeles_PlayerThread_NORM_PRIORITY 5L
#undef com_example_SanAngeles_PlayerThread_MAX_PRIORITY
#define com_example_SanAngeles_PlayerThread_MAX_PRIORITY 10L
#undef com_example_SanAngeles_PlayerThread_MAXMODSIZE
#define com_example_SanAngeles_PlayerThread_MAXMODSIZE 60000L
#undef com_example_SanAngeles_PlayerThread_BUFFERSIZE
#define com_example_SanAngeles_PlayerThread_BUFFERSIZE 40000L
#undef com_example_SanAngeles_PlayerThread_NUMPACKETS
#define com_example_SanAngeles_PlayerThread_NUMPACKETS 2L
#undef com_example_SanAngeles_PlayerThread_PACKETSIZE
#define com_example_SanAngeles_PlayerThread_PACKETSIZE 20000L
#undef com_example_SanAngeles_PlayerThread_NUM_RATES
#define com_example_SanAngeles_PlayerThread_NUM_RATES 5L
/*
 * Class:     com_example_SanAngeles_PlayerThread
 * Method:    ModPlug_Init
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_SanAngeles_PlayerThread_ModPlug_1Init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_SanAngeles_PlayerThread
 * Method:    ModPlug_JLoad
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_SanAngeles_PlayerThread_ModPlug_1JLoad
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_example_SanAngeles_PlayerThread
 * Method:    ModPlug_JGetName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_SanAngeles_PlayerThread_ModPlug_1JGetName
  (JNIEnv *, jobject);

/*
 * Class:     com_example_SanAngeles_PlayerThread
 * Method:    ModPlug_JNumChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_SanAngeles_PlayerThread_ModPlug_1JNumChannels
  (JNIEnv *, jobject);

/*
 * Class:     com_example_SanAngeles_PlayerThread
 * Method:    ModPlug_JGetSoundData
 * Signature: ([SI)I
 */
JNIEXPORT jint JNICALL Java_com_example_SanAngeles_PlayerThread_ModPlug_1JGetSoundData
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     com_example_SanAngeles_PlayerThread
 * Method:    ModPlug_JUnload
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_SanAngeles_PlayerThread_ModPlug_1JUnload
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_example_SanAngeles_PlayerThread
 * Method:    ModPlug_CloseDown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_SanAngeles_PlayerThread_ModPlug_1CloseDown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
